# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch


# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.1300, 0.2189, 0.0932, 0.9217, 0.3884, 0.6555, 0.0306],
        [0.3923, 0.8243, 0.8860, 0.2967, 0.8713, 0.4989, 0.2655],
        [0.4897, 0.8657, 0.5029, 0.8056, 0.8937, 0.6445, 0.2114],
        [0.9409, 0.4193, 0.2843, 0.1287, 0.2516, 0.1864, 0.1980],
        [0.9014, 0.9464, 0.9443, 0.5766, 0.5885, 0.7644, 0.8448],
        [0.9105, 0.7092, 0.2618, 0.6415, 0.7353, 0.3997, 0.1308],
        [0.5267, 0.0931, 0.7538, 0.3593, 0.9493, 0.2475, 0.3004]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [18]:
# Create another random tensor
tensor_2 = torch.rand(1,7)
tensor_2
# Perform matrix multiplication
tensor_2_transpose = torch.transpose(tensor_2, 1, 0)
tensor_2_transpose

tensor_matmul = torch.matmul(tensor, tensor_2_transpose)
tensor_matmul


tensor([[0.7526],
        [1.9457],
        [1.8606],
        [1.1916],
        [2.4021],
        [1.6659],
        [1.4858]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [27]:
# Set manual seed
import random
RANDOM_SEED = 42


# Create two random tensors
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(7, 7)
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(7, 1)
print("random_tensor_C:\n",random_tensor_C, "\n", "random_tensor_D:\n", random_tensor_D)
# Matrix multiply tensors

matmul = torch.matmul(random_tensor_C, random_tensor_D)
matmul


random_tensor_C:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]]) 
 random_tensor_D:
 tensor([[0.8823],
        [0.9150],
        [0.3829],
        [0.9593],
        [0.3904],
        [0.6009],
        [0.2566]])


tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [31]:
# Set random seed on the GPU
if torch.cuda.is_available:
  print('cuda')
  print('i love you')
else:
  print('cpu')


cuda
i love you


In [35]:
torch.manual_seed(seed=1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [46]:
# Set random seed
torch.manual_seed(seed=1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# Create two random tensors on GPU
tensor1 = torch.rand(2,3).to(device)
tensor2 = torch.rand(2,3).to(device)
print(tensor1,'\n', tensor2)


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') 
 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [68]:
# Perform matmul on tensor_A and tensor_B
x = torch.matmul(tensor1, tensor2.T)
print(x)
y = torch.matmul(tensor1, torch.transpose(tensor2,1,0))
print(y)
print(x.ndim, x.shape)



tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')
tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')
2 torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [64]:
# Find max
print(torch.max(x))
# Find min
print(torch.min(x))

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [66]:
# Find arg max
print(torch.argmax(x))

# Find arg min
print(torch.torch.argmin(x))

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')


In [74]:
x[1,1]

tensor(0.5617, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [79]:
# Set seed
RANDOM_SEED = 42

# Create random tensor
tensor3 = torch.rand(1, 1, 1, 10)


# Remove single dimensions
tensor4 = torch.squeeze(tensor3)

# Print out tensors and their shapes
print(tensor3, tensor3.shape)
print(tensor4, tensor4.shape)

tensor([[[[0.6839, 0.7658, 0.9149, 0.3993, 0.1100, 0.2541, 0.4333, 0.4451,
           0.4966, 0.7865]]]]) torch.Size([1, 1, 1, 10])
tensor([0.6839, 0.7658, 0.9149, 0.3993, 0.1100, 0.2541, 0.4333, 0.4451, 0.4966,
        0.7865]) torch.Size([10])
